spring:
  application:
    name: email-service
  mvc:
    servlet:
      path: /email-service # localhost:8080/email-service
#   datasource:
#     url: jdbc:mysql://localhost:3306/user_database
#     username: username
#     password: Password!
#     driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: edusphere.redis.cache.windows.net
    port: 6379
    password: kQuDQGa8IBsdwlycfnJ0ymFQpr3FgKnjFAzCaKnvfr8=
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: email-exchange
      routing-key: verificationKey
      default-receive-queue: email-queue
  mail:
    host: smtp.gmail.com
    port: 587
    username: forum5668@gmail.com
    password: cotvlzczmtlrquts
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
    protocol: smtp
    default-encoding: UTF-8

server:
  port: 8845

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
