spring:
  application:
    name: message-service
  mvc:
    servlet:
      path: /message-service
  datasource:
    url: jdbc:mysql://localhost:3306/message_database
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb+srv://mongo_user:VRWqiLvr7aFQHtQ5@mic-s-yours.ygs8hdy.mongodb.net/?retryWrites=true&w=majority
      database: Mic-s-yours

server:
  port: 8084

jwt:
  secretKey: "reddit"

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka