spring:
  application:
    name: history-service
  mvc:
    servlet:
      path: /history-service
  datasource:
    url: jdbc:mysql://localhost:3306/history_database
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secretKey: "reddit"

server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka